<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("job_listings")->insert([
            [
                "name" => "Proyecto LA NUBE (Torre y Villas)",
                "company_id"=> 1,
                "address" => "Blvd Sofia s/n, Col. Valle del Campestre, San Pedro Garza García, N.L.",
                "period" => "Agosto 2019",
                "position"=> "Residente de Obra",
                "work"=> "Instalaciones Hidrosanitarias y Pluvial",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción del Edificio para la Recuperación de Áreas Médicas y Ampliación del Servicio de Urgencias del Instituto Nacional de Rehabilitación Luis Guillermo Ibarra Ibarra Construcción de la red de MANO DE OBRA PARA LAS Instalaciones Eléctricas: Alumbrado, Contactos, Alimentadores Generales, Sistema de Tierras, Pararrayos (MANO DE OBRA). ",
                "company_id" => 2,
                "address" => "CALZADA MÉXICO XOCHIMILCO No. 289, COLONIA ARENAL DE GUADALUPE, DELEGACIÓN TLALPAN, C.P. 14389, CIUDAD DE MÉXICO",
                "period" => "Marzo 2019 - Agosto 2019",
                "position"=> "Residente de Obra",
                "work"=> "Instalaciones Eléctricas",
                "created_at" => now(),
            ],
            [
                "name" => "Hospital de 30 Camas de Cuautepec",
                "company_id" => 3,
                "address" => "Av, Puerto de Mazatlán s/n La Pastora, Del GAM, CDMX",
                "period" => "Septiembre 2018 - Febrero 2019",
                "position"=> "Residente de Obra",
                "work"=> "Instalaciones Hidrosanitarias, PCI, Pluviales, Agua Helada/Agua Caliente",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción Nueva Terminal del Aeropuerto de Acapulco",
                "company_id" => 2,
                "address" => "Boulevard de Las Naciones s/n Col. Los Amates, Punta Diamante, Acapulco Guerrero",
                "period" => "Mayo 2017 - Julio 2018",
                "position"=> "Residente de Obra",
                "work"=> "Instalaciones Hidrosanitarias",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción/Remodelación y Ampliación del Estadio de Futbol Nemecio Diez",
                "company_id" => 2,
                "address" => "Avenida Constituyentes Poniente #1000, col. Merced, Toluca, Estado de México",
                "period" => "Marzo 2017 - Mayo 2017",
                "position"=> "Apoyo para la Elaboración de planos As-built",
                "work"=> "Instalaciones Hidrosanitarias",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción de HOSPITAL Privado Plus de 21",
                "company_id" => 4,
                "address" => "Carretera Campeche-Lerma km 1, Municipio de Campeche, Fracc. Campeche Country Club. CAMPECHE",
                "period" => "Agosto 2016 - Diciembre 2016",
                "position"=> "Jefe de Departamento de Instalaciones Eléctricas",
                "work"=> "Coordinación de generadores, estimaciones",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción de Centro de Justicia de Oaxaca",
                "company_id" => 5,
                "address" => "Ixtlán de Juárez Municipio de Oaxaca, OAXACA",
                "period" => "Abril 2016 - Junio 2016",
                "position"=> "Residente de Instalaciones Eléctricas e Instalaciones Hidrosanitarias ",
                "work"=> "Instalaciones Eléctricas e Instalaciones Hidrosanitarias ",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción de HOSPITAL Privado Plus de 21",
                "company_id" => 4,
                "address" => "Carretera Campeche-Lerma km 1, Municipio de Campeche, Fracc. Campeche Country Club. CAMPECHE",
                "period" => "Septiembre 2015 - Marzo 2016",
                "position"=> "Jefe de Departamento de Instalaciones Eléctricas",
                "work"=> "Coordinación de generadores, estimaciones",
                "created_at" => now(),
            ],
            [
                "name" => "Análisis, Propuesta y Cuantificación Para el Proyecto de Nave Industrial en Querétaro. ",
                "company_id" => 6,
                "address" => "",
                "period" => "Mayo 2015 - Agosto 2015",
                "position"=> "Analista",
                "work"=> "Cuantificación en Instalaciones Hidrosanitarias y Protección Contra Incendio, para generar presupuestos con matrices de P.U.",
                "created_at" => now(),
            ],
            [
                "name" => "Análisis, Propuesta y Cuantificación Para el Proyecto de Tren Ligero de Guadalajara, Jalisco",
                "company_id" => 6,
                "address" => "",
                "period" => "Mayo 2015 - Agosto 2015",
                "position"=> "Analista",
                "work"=> "Cuantificación en Instalaciones Hidrosanitarias y Protección Contra Incendio, para generar presupuestos con matrices de P.U.",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción de HOSPITAL MATERNO INFANTIL",
                "company_id" => 6,
                "address" => "AV. CENTRAL S/N FRACCIONAMIENTO MUNDO MAYA, CIUDAD DEL CARMEN CAMPECHE",
                "period" => "Diciembre 2013 - Mayo 2015",
                "position"=> "Jefe de Departamento de Instalaciones Hidrosanitarias",
                "work"=> "Coordinación de la elaboración de generadores, Estimaciones y ejecución de trabajos en obra",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción y Equipamiento Segunda Etapa de la Nueva Torre de Hospitalización INCAN.",
                "company_id" => 7,
                "address" => "Av. San Fernando No.2, Col. Barrio Del Niño Jesús, Delegación Tlalpan, México CDMX",
                "period" => "Abril 2013 - Noviembre 2013",
                "position"=> "Apoyo en el departamento de elaboración de Generadores Instalación Hidrosanitaria y Eléctrica",
                "work"=> "Obra Civil (tablaroca, herrería)",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción y Equipamiento Segunda Etapa de la Nueva Torre de Hospitalización INCAN.",
                "company_id" => 6,
                "address" => "Av. San Fernando No.2, Col. Barrio Del Niño Jesús, Delegación Tlalpan, México CDMX",
                "period" => "Abril 2013 - Noviembre 2013",
                "position"=> "Apoyo en el departamento de elaboración de Generadores Instalación Hidrosanitaria y Eléctrica",
                "work"=> "Instalación Hidrosanitaria y Eléctrica",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción y Equipamiento Segunda Etapa de la Nueva Torre de Hospitalización INCAN.",
                "company_id" => 8,
                "address" => "Av. San Fernando No.2, Col. Barrio Del Niño Jesús, Delegación Tlalpan, México CDMX",
                "period" => "Enero 2013 - Marzo 2013",
                "position"=> "Apoyo en el departamento de elaboración de Generadores",
                "work"=> "Elaboración de Generadores",
                "created_at" => now(),
            ],
            [
                "name" => "Torre de Especialidades Dr. Manuel Gea González Segunda y Tercera Etapa",
                "company_id" => 9,
                "address" => "Calzada de Tlalpan # 4800, Colonia Sección XVI, Del. Tlalpan, Ciudad de México",
                "period" => "Septiembre 2011 - Diciembre 2012",
                "position"=> "Encargado de obra, responsable en el departamento de control de Estimaciones y Generadores. Residente de Obra",
                "work"=> "Estimaciones y Generadores",
                "created_at" => now(),
            ],
            [
                "name" => "Superama Bosques-Remodelación Partial",
                "company_id" => 10,
                "address" => "Bosques de Duraznos 187, Bosques de las Lomas. Ciudad de México",
                "period" => "Marzo 2011 - Julio 2011",
                "position"=> "Jefe de Supervisión de Obra",
                "work"=> "Supervisión de Obra",
                "created_at" => now(),
            ],
            [
                "name" => "Cine Centros Digitales",
                "company_id" => 11,
                "address" => "Ciudad de México",
                "period" => "2010",
                "position"=> "Coordinador/Colaborador de proyecto y diseño esquemático a nivel urbano y arquitectónico",
                "work"=> "Diseño esquemático",
                "created_at" => now(),
            ],
            [
                "name" => "Proyectos Ambientales GST AutoLeather",
                "company_id" => 11,
                "address" => "León, Gto.; Saltillo, Coah.; Nuevo Laredo, Tamps",
                "period" => "2010",
                "position"=> "Coordinador/Colaborador de proyecto y diseño esquemático a nivel urbano y arquitectónico; propuestas de prototipos para aislantes de calor y ruido.",
                "work"=> "Diseño esquemático",
                "created_at" => now(),
            ],
            [
                "name" => "Plan de Manejo de Agua en Parque Metropolitano de Guadalajara",
                "company_id" => 11,
                "address" => "Municipio de Zapopan, Jal",
                "period" => "2010",
                "position"=> "Colaborador de proyecto y diseño esquemático a nivel urbano y arquitectónico",
                "work"=> "Diseño esquemático",
                "created_at" => now(),
            ],
            [
                "name" => "Plan Maestro Ambiental y Urbano",
                "company_id" => 11,
                "address" => "Veracruz, Mex",
                "period" => "2009-2010",
                "position"=> "Colaborador de proyecto y diseño esquemático a nivel urbano y arquitectónico.",
                "work"=> "Diseño esquemático",
                "created_at" => now(),
            ],
            [
                "name" => "Propuesta de ahorro de energía eléctrica, gas y agua en Talleres de autobuses con oficinas. Grupo HP del Occidente",
                "company_id" => 11,
                "address" => "Santa Fe, México, CDMX",
                "period" => "2008-2009",
                "position"=> "Apoyo técnico",
                "work"=> "Colaboración y Apoyo técnico",
                "created_at" => now(),
            ],
            [
                "name" => "Plan Maestro del Parque Expo-Bicentenario, Gobierno del Estado de Guanajuato",
                "company_id" => 11,
                "address" => "Silao, Gto.",
                "period" => "2008-2009",
                "position"=> "Apoyo técnico",
                "work"=> "Dibujar planos, elaborar tablas de superficies y porcentajes en Excel, presentaciones en power point, photoshop, corel draw, etc.",
                "created_at" => now(),
            ],
            [
                "name" => "Parque Ávila Camacho–Proyecto de Renovación Urbana del Entorno del Gimnasio Ávila Camacho",
                "company_id" => 11,
                "address" => "Guadalajara, Jalisco",
                "period" => "2008",
                "position"=> "",
                "work"=> "",
                "created_at" => now(),
            ],
            [
                "name" => "Hotelito Desconocido–Plan Maestro de Manejo Ambiental",
                "company_id" => 11,
                "address" => "La Cruz de Loreto, Municipio de Tomatlan, Jalisco",
                "period" => "2008",
                "position"=> "Colaborador",
                "work"=> "Elaboración de planos, documentos (memorias descriptivas) y presentaciones en PDF y Power Point",
                "created_at" => now(),
            ],
            [
                "name" => "Complejo Turístico/Residencial El Dorado Ranch, Obra principal: Plan Maestro Ambiental y Urbano",
                "company_id" => 12,
                "address" => "",
                "period" => "Junio 2004 - 2008",
                "position"=> "Arquitecto",
                "work"=> "Actividades relacionadas a trámites ante Autoridades del Municipio de Mexicali y el Gobierno del Edo. de Baja California ",
                "created_at" => now(),
            ],
            [
                "name" => "REMODELACIÓN, AMPLIACIÓN Y CONSTRUCCIÓN DE PISOS Y LABORATORIO EN NAVE INDUSTRIAL",
                "company_id" => 13,
                "address" => "Industrias Alen del Sureste, carretera Villahermosa-Frontera km. 5, Industrial 2da etapa, Municipio del Centro, Villahermosa, Tab. México",
                "period" => "Mayo 2004 - Junio 2004",
                "position"=> "Residente de Obra",
                "work"=> "Residente de obra, control de personal y su respectiva nomina, así como el trato directo con la contratación de suministro de concreto, de material para la construcción, maquinaria ligera, reportes de obra en bitácora, toma de decisiones en obra, administración local de obra y de la estancia de los trabajadores.",
                "created_at" => now(),
            ],
            [
                "name" => "CONSTRUCCIÓN DE GUARNICIONES, DIVERSAS UBICACIONES",
                "company_id" => 14,
                "address" => "Tlalpan, CDMX",
                "period" => "Agosto 2003 - Marzo 2004",
                "position"=> "Supervisor de Obra",
                "work"=> "trabajos de supervisión en obra y de oficina",
                "created_at" => now(),
            ],
            [
                "name" => "CONSTRUCCIÓN DE BANQUETAS, DIVERSAS UBICACIONES",
                "company_id" => 14,
                "address" => "Tlalpan, CDMX",
                "period" => "Noviembre 2002 - Marzo 2003",
                "position"=> "Supervisor de Obra",
                "work"=> "trabajos de supervisión en obra y de oficina",
                "created_at" => now(),
            ],
            [
                "name" => "Construcción de Casa Habitación Residencial",
                "company_id" => 15,
                "address" => "Calle Pirámide # 3; 3b; y 10, Pueblo Sto. Tomas Ajusco, Delegación Tlalpan",
                "period" => "2002",
                "position"=> "Dibujante sobre modificaciones de obra",
                "work"=> "Dibujante",
                "created_at" => now(),
            ],            
        ]);
    }
}
